version: '3'
services:
  app:
    build:
      context: ./site
      dockerfile: ../docker/app.dockerfile
    working_dir: /var/www
    restart: always
    volumes:
      - ./site:/var/www
#    environment:
#      - "DB_PORT=3306"
#      - "DB_HOST=bravos_database_1"
    networks:
      - production-network
    depends_on:
      - "database"
  web:
    build:
      context: ./docker
      dockerfile: web.dockerfile
    working_dir: /var/www
    restart: always
    volumes:
      - ./site:/var/www
    ports:
      - 80:80
    networks:
      - production-network
    depends_on:
      - "app"
  database:
    image: mysql
    command: ['--default-authentication-plugin=mysql_native_password', '--innodb_use_native_aio=0','--lower_case_table_names=1']
    restart: always
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=bravos"
      - "MYSQL_USER=csarda"
      - "MYSQL_PASSWORD=sarda88"
      - "MYSQL_ROOT_PASSWORD=sarda88"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
    networks:
      - production-network
    ports:
      - "3306:3306"
  redis:
    image: redis
    restart: always
    volumes:
      - ./redis/data:/data
    networks:
      - production-network
    ports:
      - "6379:6379"
networks:
  production-network:
    driver: bridge